# Generated by Django 2.2.2 on 2019-06-17 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('nombre_tipo', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_item', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cantidad', models.IntegerField()),
                ('tipo_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Tipo')),
            ],
        ),
    ]
